### ISSUE TITLE
add debug mode?

### ISSUE THREAD

**Issue by AlJohri** [legal90/awscurl#6]
I'm running into a strange issue where if I run:

```
awscurl --profile xyz --service es "https://xyz.us-east-99.es.amazonaws.com/myindex/_doc/mydocid"
```

The output is entirely blank.

If I query the same exact document ID through Kibana or using the `opensearch-cli` I get correct results.

Can we add some sort of debug mode to understand what's going on?

**Comment by legal90** [comment]
Hi @AlJohri,
In [0.2.1](https://github.com/legal90/awscurl/releases/tag/0.2.1) we have added the "include" mode (details: https://github.com/legal90/awscurl/pull/7).  Try adding `-i` param and you should at least see the returned HTTP response code. I hope it might help to troubleshoot the issue further.
